baseURL = 'https://anthropocenetimeline.com/'
languageCode = 'en-us'
title = 'Anthropocene Timeline'
defaultContentLanguage = 'en'
publishDir = 'docs'
staticDir = 'static'

[params]
author = "Alexandre Poupeau"
email = "alexandre.poupeau.contact@gmail.com"
siteName = 'Anthropocene Timeline'
images = ["/img/main/art-ipcc-curv.jpeg"]
description = "A comprehensive timeline documenting humanity's impact on Earth, exploring key events, scientific discoveries, and environmental changes that define the Anthropocene epoch."
[params.navigation]
  help = 'Help'

[languages]
  [languages.en]
    title = 'Anthropocene Timeline'
    contentDir = "content/en"
    languageName = "English"
    weight = 1
    copyright = 'Anthropocene Timeline. All rights reserved.'
    [languages.en.params]
      languageShort = "EN"
  [languages.fr]
    title = "La frise chronologique de l'Anthropocène"
    contentDir = "content/fr"
    languageName = "Français"
    copyright = 'Anthropocene Timeline. Tous droits réservés.'
    weight = 2
    [languages.fr.params]
      languageShort = "FR"
      [languages.fr.params.navigation]
        help = 'Aide'
  [languages.es]
    title = 'La línea de tiempo del Anthropoceno'
    contentDir = "content/es"
    languageName = "Español"
    copyright = 'Anthropocene Timeline. Todos los derechos reservados.'
    weight = 3
    [languages.es.params]
      languageShort = "ES"

disableKinds = ["taxonomy"]
